// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Summoner struct {
	ID            pgtype.UUID
	Puuid         string
	AccountID     string
	SummonerID    string
	Level         int64
	ProfileIconID int32
	Name          string
	LastRevision  pgtype.Timestamp
	TimeStamp     pgtype.Timestamp
}
