// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Summoner struct {
	ID            pgtype.UUID
	Puuid         pgtype.Text
	AccountID     pgtype.Text
	SummonerID    pgtype.Text
	Level         interface{}
	ProfileIconID pgtype.Int4
	Name          pgtype.Text
	LastRevision  pgtype.Timestamp
	TimeStamp     pgtype.Timestamp
}
