// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SummonerRecord struct {
	RecordID      pgtype.UUID
	RecordDate    pgtype.Timestamp
	AccountID     string
	ProfileIconID int32
	RevisionDate  int64
	Name          string
	ID            string
	Puuid         string
	SummonerLevel int64
}
