// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: summoner.proto

package riot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummonerByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SummonerByNameRequest) Reset() {
	*x = SummonerByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_summoner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummonerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonerByNameRequest) ProtoMessage() {}

func (x *SummonerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summoner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonerByNameRequest.ProtoReflect.Descriptor instead.
func (*SummonerByNameRequest) Descriptor() ([]byte, []int) {
	return file_summoner_proto_rawDescGZIP(), []int{0}
}

func (x *SummonerByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SummonerByPuuidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puuid string `protobuf:"bytes,1,opt,name=puuid,proto3" json:"puuid,omitempty"`
}

func (x *SummonerByPuuidRequest) Reset() {
	*x = SummonerByPuuidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_summoner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummonerByPuuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonerByPuuidRequest) ProtoMessage() {}

func (x *SummonerByPuuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summoner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonerByPuuidRequest.ProtoReflect.Descriptor instead.
func (*SummonerByPuuidRequest) Descriptor() ([]byte, []int) {
	return file_summoner_proto_rawDescGZIP(), []int{1}
}

func (x *SummonerByPuuidRequest) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

type SummonerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puuid         string `protobuf:"bytes,1,opt,name=puuid,proto3" json:"puuid,omitempty"`
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SummonerId    string `protobuf:"bytes,3,opt,name=summoner_id,json=summonerId,proto3" json:"summoner_id,omitempty"`
	Level         int64  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	ProfileIconId int32  `protobuf:"varint,5,opt,name=profile_icon_id,json=profileIconId,proto3" json:"profile_icon_id,omitempty"`
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	LastRevision  int64  `protobuf:"varint,7,opt,name=last_revision,json=lastRevision,proto3" json:"last_revision,omitempty"`
}

func (x *SummonerResponse) Reset() {
	*x = SummonerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_summoner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummonerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonerResponse) ProtoMessage() {}

func (x *SummonerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_summoner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonerResponse.ProtoReflect.Descriptor instead.
func (*SummonerResponse) Descriptor() ([]byte, []int) {
	return file_summoner_proto_rawDescGZIP(), []int{2}
}

func (x *SummonerResponse) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *SummonerResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SummonerResponse) GetSummonerId() string {
	if x != nil {
		return x.SummonerId
	}
	return ""
}

func (x *SummonerResponse) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SummonerResponse) GetProfileIconId() int32 {
	if x != nil {
		return x.ProfileIconId
	}
	return 0
}

func (x *SummonerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SummonerResponse) GetLastRevision() int64 {
	if x != nil {
		return x.LastRevision
	}
	return 0
}

var File_summoner_proto protoreflect.FileDescriptor

var file_summoner_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2b, 0x0a, 0x15, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a,
	0x16, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x50, 0x75, 0x75, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x22, 0xdf, 0x01,
	0x0a, 0x10, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75,
	0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x26,
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x32,
	0x7f, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x35, 0x0a, 0x06, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x53, 0x75, 0x6d,
	0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x42, 0x79, 0x50, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x50,
	0x75, 0x75, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x53, 0x75,
	0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x61, 0x6e, 0x6b, 0x31, 0x7a, 0x65, 0x6e, 0x2f, 0x79, 0x75, 0x6a, 0x69, 0x6e, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x69, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_summoner_proto_rawDescOnce sync.Once
	file_summoner_proto_rawDescData = file_summoner_proto_rawDesc
)

func file_summoner_proto_rawDescGZIP() []byte {
	file_summoner_proto_rawDescOnce.Do(func() {
		file_summoner_proto_rawDescData = protoimpl.X.CompressGZIP(file_summoner_proto_rawDescData)
	})
	return file_summoner_proto_rawDescData
}

var file_summoner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_summoner_proto_goTypes = []interface{}{
	(*SummonerByNameRequest)(nil),  // 0: SummonerByNameRequest
	(*SummonerByPuuidRequest)(nil), // 1: SummonerByPuuidRequest
	(*SummonerResponse)(nil),       // 2: SummonerResponse
}
var file_summoner_proto_depIdxs = []int32{
	0, // 0: SummonerQuery.ByName:input_type -> SummonerByNameRequest
	1, // 1: SummonerQuery.ByPuuid:input_type -> SummonerByPuuidRequest
	2, // 2: SummonerQuery.ByName:output_type -> SummonerResponse
	2, // 3: SummonerQuery.ByPuuid:output_type -> SummonerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_summoner_proto_init() }
func file_summoner_proto_init() {
	if File_summoner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_summoner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummonerByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_summoner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummonerByPuuidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_summoner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummonerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_summoner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summoner_proto_goTypes,
		DependencyIndexes: file_summoner_proto_depIdxs,
		MessageInfos:      file_summoner_proto_msgTypes,
	}.Build()
	File_summoner_proto = out.File
	file_summoner_proto_rawDesc = nil
	file_summoner_proto_goTypes = nil
	file_summoner_proto_depIdxs = nil
}
