// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SoloqRecord struct {
	RecordID     pgtype.UUID      `json:"record_id"`
	RecordDate   pgtype.Timestamp `json:"record_date"`
	LeagueID     pgtype.Text      `json:"league_id"`
	SummonerID   pgtype.Text      `json:"summoner_id"`
	SummonerName pgtype.Text      `json:"summoner_name"`
	Tier         pgtype.Text      `json:"tier"`
	Rank         pgtype.Text      `json:"rank"`
	LeaguePoints pgtype.Int4      `json:"league_points"`
	Wins         pgtype.Int4      `json:"wins"`
	Losses       pgtype.Int4      `json:"losses"`
}

type SummonerRecord struct {
	RecordID      pgtype.UUID      `json:"record_id"`
	RecordDate    pgtype.Timestamp `json:"record_date"`
	AccountID     pgtype.Text      `json:"account_id"`
	ProfileIconID pgtype.Int4      `json:"profile_icon_id"`
	RevisionDate  pgtype.Int8      `json:"revision_date"`
	Name          pgtype.Text      `json:"name"`
	ID            pgtype.Text      `json:"id"`
	Puuid         pgtype.Text      `json:"puuid"`
	SummonerLevel pgtype.Int8      `json:"summoner_level"`
}
